version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'my-secret-pw'
    ports:
      - '3306:3306'
    volumes:
      - mysqldata:/var/lib/mysql
volumes:
  mysqldata:
    external: true
