name: build-docker-image
on: workflow_dispatch
jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: cloudoneknr/hitcount
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          file: ./hitcount/Dockerfile
          push: true
          tags: cloudoneknr/hitcount:v1.0